In [1]:
%load_ext autoreload

In [2]:
%autoreload 2

In [3]:
import ReadData

In [4]:
path_file = 'Kopie van Facturen 14-06-2021 10_39_06.xlsx'

In [5]:
app = ReadData.ReadData(path_file=path_file)

In [6]:
app.process_customers()

In [7]:
first_df = app.get_dataframe_from_customer_list()

In [8]:
first_df

,Debiteur nr.,Klant,Abonnement,Totaal betaald,Gem. Prijs,Maanden boven bundel,Aantal maanden actief,Gem. Gebruik,Mediaan gebruik,Modus gebruik,Hoogste gebruik,Laatst gefactureerde datum,Subscription Object
0,12131.0,@ctief Werk Detachering BV (CAOWijzer),Light,75.0,25.00,0,3,0.00,0,0,0,31-03-2020,"[Subscription(price=25.0, free_clicks=0, extra..."
1,12152.0,365werk (CAOWijzer),Light,568.5,33.44,6,17,8.94,8,3,24,31-05-2021,"[Subscription(price=25.0, free_clicks=10, extr..."
2,12696.0,3D Salaris B.V. (CAOWijzer),Standard,882.5,51.91,1,17,7.18,5,1,38,31-05-2021,"[Subscription(price=50.0, free_clicks=5, extra..."
3,12661.0,400FlexCollab,None,0.0,0.00,0,3,9.67,10,8,11,31-05-2021,"[Subscription(price=0, free_clicks=10, extra_c..."
4,12116.0,4Works B.V.,Standard,1810.0,106.47,14,17,56.59,50,34,107,31-05-2021,"[Subscription(price=0, free_clicks=60, extra_c..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,12475.0,Yes Personeelsdiensten BV,Light,446.0,26.24,1,17,2.88,1,1,16,31-05-2021,"[Subscription(price=25.0, free_clicks=4, extra..."
390,12288.0,Your Career (Caowijzer),Standard,800.0,47.06,0,17,4.71,3,1,13,31-05-2021,"[Subscription(price=0.0, free_clicks=0, extra_..."
391,12154.0,YSER BV (CAOWijzer),Light,435.5,25.62,2,17,4.47,4,5,12,31-05-2021,"[Subscription(price=25.0, free_clicks=1, extra..."
392,12008.0,Zebra Uitzendbureau BV (CAOWijzer),Standard,945.0,55.59,5,17,18.53,18,13,37,31-05-2021,"[Subscription(price=50.0, free_clicks=25, extr..."
393,11553.0,Zendèl BV,None,0.0,0.00,0,1,0.00,0,0,0,29-02-2020,"[Subscription(price=0, free_clicks=0, extra_cl..."

In [9]:
light_threshold = 17.14
standard_threshold = 45
column_name = 'Gem. Gebruik'
updated_df = ReadData.update_subscriptions(data_df=first_df, column_to_use=column_name, light_threshold=light_threshold, standard_threshold=standard_threshold)

In [10]:
# updated_df

In [11]:
updated_df = app.update_customer_list(updated_df)

In [12]:
new_updated_df = app.get_dataframe_from_customer_list()
new_updated_df.to_excel('Dataset met update abonnement.xlsx')

In [13]:
new_updated_df

,Debiteur nr.,Klant,Abonnement,Totaal betaald,Gem. Prijs,Maanden boven bundel,Aantal maanden actief,Gem. Gebruik,Mediaan gebruik,Modus gebruik,Hoogste gebruik,Laatst gefactureerde datum,Subscription Object
0,12131.0,@ctief Werk Detachering BV (CAOWijzer),Light,75.0,25.00,0,3,0.00,0,0,0,31-03-2020,"[Subscription(price=25.0, free_clicks=0, extra..."
1,12152.0,365werk (CAOWijzer),Light,568.5,33.44,6,17,8.94,8,3,24,31-05-2021,"[Subscription(price=25.0, free_clicks=10, extr..."
2,12696.0,3D Salaris B.V. (CAOWijzer),Light,568.5,33.44,3,17,7.18,5,1,38,31-05-2021,"[Subscription(price=25.0, free_clicks=5, extra..."
3,12661.0,400FlexCollab,None,0.0,0.00,3,3,9.67,10,8,11,31-05-2021,"[Subscription(price=0, free_clicks=10, extra_c..."
4,12116.0,4Works B.V.,Premium,1810.0,106.47,2,17,56.59,50,34,107,31-05-2021,"[Subscription(price=100.0, free_clicks=60, ext..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,12475.0,Yes Personeelsdiensten BV,Light,446.0,26.24,1,17,2.88,1,1,16,31-05-2021,"[Subscription(price=25.0, free_clicks=4, extra..."
390,12288.0,Your Career (Caowijzer),Light,435.5,25.62,1,17,4.71,3,1,13,31-05-2021,"[Subscription(price=25.0, free_clicks=0, extra..."
391,12154.0,YSER BV (CAOWijzer),Light,435.5,25.62,2,17,4.47,4,5,12,31-05-2021,"[Subscription(price=25.0, free_clicks=1, extra..."
392,12008.0,Zebra Uitzendbureau BV (CAOWijzer),Standard,945.0,55.59,5,17,18.53,18,13,37,31-05-2021,"[Subscription(price=50.0, free_clicks=25, extr..."
393,11553.0,Zendèl BV,None,0.0,0.00,0,1,0.00,0,0,0,29-02-2020,"[Subscription(price=0, free_clicks=0, extra_cl..."

In [14]:
# first_total_costs = first_df['Totaal betaald'].sum()
# print('First costs: ', int(first_total_costs))
# updated_total_costs = updated_df['Totaal betaald'].sum()
# print('Updated costs: ', int(updated_total_costs))
# new_updated_total_costs = new_updated_df['Totaal betaald'].sum()
# print('New updated costs: ', int(new_updated_total_costs))

In [15]:
light = ['Light', 25., 10, 5.]
standard = ['Standard', 50., 25, 4.]
premium = ['Premium', 100, 75, 3.]
data_to_use = [light, standard, premium]

In [16]:
# creating new dataframe with the newly chosen parameters
for customer in app.customers:
    customer.find_and_change_subscription_with_parameters(data=data_to_use)
    customer.perform_calculations()

In [17]:
new_parameter_df = app.get_dataframe_from_customer_list()

In [18]:
new_parameter_df.to_excel('Dataset met nieuwe parameters.xlsx')

In [19]:
new_parameter_df

,Debiteur nr.,Klant,Abonnement,Totaal betaald,Gem. Prijs,Maanden boven bundel,Aantal maanden actief,Gem. Gebruik,Mediaan gebruik,Modus gebruik,Hoogste gebruik,Laatst gefactureerde datum,Subscription Object
0,12131.0,@ctief Werk Detachering BV (CAOWijzer),Light,75.0,25.00,0,3,0.00,0,0,0,31-03-2020,"[Subscription(price=25.0, free_clicks=0, extra..."
1,12152.0,365werk (CAOWijzer),Light,630.0,37.06,6,17,8.94,8,3,24,31-05-2021,"[Subscription(price=25.0, free_clicks=10, extr..."
2,12696.0,3D Salaris B.V. (CAOWijzer),Light,630.0,37.06,3,17,7.18,5,1,38,31-05-2021,"[Subscription(price=25.0, free_clicks=5, extra..."
3,12661.0,400FlexCollab,None,0.0,0.00,3,3,9.67,10,8,11,31-05-2021,"[Subscription(price=0, free_clicks=10, extra_c..."
4,12116.0,4Works B.V.,Premium,1865.0,109.71,2,17,56.59,50,34,107,31-05-2021,"[Subscription(price=100, free_clicks=60, extra..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
389,12475.0,Yes Personeelsdiensten BV,Light,455.0,26.76,1,17,2.88,1,1,16,31-05-2021,"[Subscription(price=25.0, free_clicks=4, extra..."
390,12288.0,Your Career (Caowijzer),Light,440.0,25.88,1,17,4.71,3,1,13,31-05-2021,"[Subscription(price=25.0, free_clicks=0, extra..."
391,12154.0,YSER BV (CAOWijzer),Light,440.0,25.88,2,17,4.47,4,5,12,31-05-2021,"[Subscription(price=25.0, free_clicks=1, extra..."
392,12008.0,Zebra Uitzendbureau BV (CAOWijzer),Standard,1002.0,58.94,5,17,18.53,18,13,37,31-05-2021,"[Subscription(price=50.0, free_clicks=25, extr..."
393,11553.0,Zendèl BV,None,0.0,0.00,0,1,0.00,0,0,0,29-02-2020,"[Subscription(price=0, free_clicks=0, extra_cl..."